parameters:
#    namshi_utility.example.class: Namshi\UtilityBundle\Example

services:
#    namshi_utility.example:
#        class: %namshi_utility.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
